### ISSUE TITLE
hdf5 1.8.9 does not support gcc 4.9.

### ISSUE THREAD

**Issue by sgkim126** [amznlabs/amazon-dsstne#71]
[Setup guide](https://github.com/amznlabs/amazon-dsstne/blob/master/docs/getting_started/setup.md#hdf5-setup) saids you used hdf5 1.8.9, but it was broken and cannot be compiled(with both gcc-4.9 and gcc-5).
```
th5s.c:733:9: error: C++ style comments are not allowed in ISO C90
         // ret = H5Pset_alloc_time(plist_id, alloc_time);
         ^
th5s.c:733:9: error: (this will be reported only once per input file)
```

I think you should update document to use 1.8.12 that was fixed this compile error.

**Comment by tristanpenman** [comment]
@sgkim126, thanks for letting us know about the issue.

Upgrading to 1.8.12 sounds like the right approach here. But I don't recall having any issues with 1.8.9, and would like to reproduce the issue before making the change. Can you tell me which OS / distribution you are using so that I can properly document the change?

**Comment by sgkim126** [comment]
@tristanpenman 
I used ubuntu 16.04, got hdf5 from ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4/hdf5-1.8.9.tar.gz, and installed gcc 4.9 and 5 with apt-get.
It occurred on both my local machine and aws ubuntu server 16.04 ami.

**Comment by scottlegrand** [comment]
What about 14.04?

**Comment by sgkim126** [comment]
@scottlegrand
I didn't test on 14.04. I'll let you know after test.

**Comment by scottlegrand** [comment]
Also Ubuntu 16.04 is not officially support in CUDA 7.5.

15.04 and 14.04 are so while I think the issue you have produced is valid,
and there's no harm in upgrading HDFS, I wouldn't rely on unsupported
versions of linux.

Every CUDA toolkit comes with a linux installation guide in its doc
directory, for 7.5 you can see it here:

http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#axzz3x7mwvZrG

**Comment by sgkim126** [comment]
It works fine with ubuntu 14.04, specifically with under gcc 4.8.
But it fails in ubuntu 15.04 who uses gcc 4.9.

Since CUDA 7.5 supports ubuntu 15.04, I think you should upgrade the hdf5 version or state the supported gcc version(4.8) and ubuntu version(14.04) in setup document.

**Comment by tristanpenman** [comment]
@sgkin126, given that 1.8.12 is a minor release and is known to fix this issue, I expect that upgrading won't be a problem for us. I'll keep this issue open while we look at that.

And as far as documentation is concerned, that can definitely be improved. Once the package update is sorted out, I'll update the documentation to include some more information regarding dependencies.
